### ISSUE TITLE
better way to connect PHPStorm with Docker on Mac 

### ISSUE THREAD

**Issue by urukalo** [code4hire/docker-dev-setup#4]
new version of docker can be connected to PHPStorm with:
`API URL: unix:///var/run/docker.sock`

**Comment by vranac** [comment]
@urukalo I can verify it is wokring in 2017.1, I'll update the docs with this as primary, and leave the socat as fallback in case on incompatiblity.

Thank you.

**Comment by vranac** [comment]
Docs have been updated.
